version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  backend:
    build: ../backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build: ../frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"