"""rbac and multi-library production hotfix

Revision ID: 0012_rbac_multi_library_hotfix
Revises: 0011_rbac_and_library_access_control
Create Date: 2026-04-02 00:30:00.000000
"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0012_rbac_multi_library_hotfix"
down_revision: Union[str, Sequence[str], None] = "0011_rbac_and_library_access_control"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE IF NOT EXISTS user_libraries (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            tenant_id INTEGER NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
            library_id INTEGER NOT NULL REFERENCES libraries(id) ON DELETE CASCADE,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            CONSTRAINT uq_user_libraries_user_library UNIQUE (user_id, library_id)
        )
        """
    )

    op.execute("CREATE INDEX IF NOT EXISTS ix_user_libraries_user_id ON user_libraries (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_libraries_tenant_id ON user_libraries (tenant_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_libraries_library_id ON user_libraries (library_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_user_libraries_user_tenant ON user_libraries (user_id, tenant_id)")

    # Ensure base RBAC roles exist for every tenant and use explicit typed NULL.
    op.execute(
        """
        INSERT INTO roles (tenant_id, library_id, code, name, description, is_system)
        SELECT DISTINCT u.tenant_id, NULL::INTEGER, 'super_admin', 'Super Admin', 'Full tenant administration', true
        FROM users u
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (tenant_id, code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO roles (tenant_id, library_id, code, name, description, is_system)
        SELECT DISTINCT u.tenant_id, NULL::INTEGER, 'librarian', 'Librarian', 'Manage catalog and circulation', true
        FROM users u
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (tenant_id, code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO roles (tenant_id, library_id, code, name, description, is_system)
        SELECT DISTINCT u.tenant_id, NULL::INTEGER, 'assistant', 'Assistant', 'Assist operations and circulation', true
        FROM users u
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (tenant_id, code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO roles (tenant_id, library_id, code, name, description, is_system)
        SELECT DISTINCT u.tenant_id, NULL::INTEGER, 'member', 'Member', 'Member-level access', true
        FROM users u
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (tenant_id, code) DO NOTHING
        """
    )

    op.execute(
        """
        INSERT INTO user_roles (user_id, role_id, tenant_id, library_id)
        SELECT u.id, r.id, u.tenant_id, NULL::INTEGER
        FROM users u
        JOIN roles r
          ON r.tenant_id = u.tenant_id
         AND r.code = lower(u.role::text)
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (user_id, role_id, library_id) DO NOTHING
        """
    )

    # Backfill: every tenant user can access all libraries in the same tenant.
    op.execute(
        """
        INSERT INTO user_libraries (user_id, tenant_id, library_id)
        SELECT u.id, u.tenant_id, l.id
        FROM users u
        JOIN libraries l ON l.tenant_id = u.tenant_id
        WHERE u.tenant_id IS NOT NULL
        ON CONFLICT (user_id, library_id) DO NOTHING
        """
    )


def downgrade() -> None:
    # Data hotfix only. Keep tables and assignments intact.
    pass
